name: phasIR
channels:
  - conda-forge
  - defaults
dependencies:
  - coveralls
  - h5py
  - imageio
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
#  - jupyter_client
#  - jupyter_console
#  - jupyter_core
#  - keras
#  - Keras-Applications==1.0.7
#  - Keras-Preprocessing==1.0.9
  - matplotlib
  - nose
  - notebook
  - numpy
  - numpy-base
  - pandas
  - pip
  - python
  - scipy
  - setuptools
  - scikit-image
  - scikit-learn
  - sphinx
#   - sphinx-rtd-theme
  - tabulate
#  - tensorflow==2.0
#  - testpath
#  - terminaltables
#  - tk
#  - pip:
#    - plotly==4.8.1
#    - tensorflow==2.0
