name: phasIR
channels:
  - conda-forge
  - defaults
dependencies:
  - coveralls
  - h5py
  - imageio
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - matplotlib
  - nose
  - notebook
  - numpy
  - numpy-base
  - pandas
  - pip
  - python
  - scipy
  - setuptools
  - scikit-image==0.18
  - scikit-learn
  - sphinx
  - tabulate
