{% set name = "phasIR" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v1.0
  git_url: https://github.com/pozzo-research-group/phasIR

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
    - h5py
    - ipywidgets
    - matplotlib
    - scipy
    - scikit-image
    - scikit-learn
  run:
    - python
    - h5py
    - numpy
    - pandas
    - matplotlib
    - scipy
    - scikit-image
    - scikit-learn


test:
  requires:
    - python
    - setuptools
    - numpy
    - pandas
    - h5py
    - ipywidgets
    - matplotlib
    - scipy
    - scikit-image
    - scikit-learn
  imports:
    - phasIR

about:
  home: https://github.com/pozzo-research-group/phasIR
  license: MIT
  license_family: MIT
  summary: Analysis for High-throughput Phase Transition Temperature Determination Using an IR Camera
